In [2]:
import numpy as np
from sklearn.metrics import pairwise_distances

In [3]:
list_A = [(461.5, 281.0), (275.0, 282.0), (200, 222.0), (300, 333.0)] #centerCount_list

In [3]:
l = [1]
len(l)

1

In [5]:
min(list_A)

(200, 222.0)

In [4]:
for C, center_First in enumerate(list_A):
    print(center_First)
    print(center_First[0])
    print("...........")
    for CC, center_Second in enumerate(list_A):
        if C != CC:
            print(center_Second)
            #P = (x,y)
            P1 = (int(center_First[0]), int(center_First[1]))  # 0
            P2 = (int(center_Second[0]), int(center_Second[1]))  # 1
            
            distance_line = np.sqrt((P2[0] - P1[0])**2 + (P2[0] - P1[1])**2)
            print('distance_line = {}'.format(str(distance_line)))
    print('_____________________________________________')

(461.5, 281.0)
461.5
...........
(275.0, 282.0)
distance_line = 186.09674903124989
(200, 222.0)
distance_line = 273.28007611240156
(300, 333.0)
distance_line = 162.1172415260018
_____________________________________________
(275.0, 282.0)
275.0
...........
(461.5, 281.0)
distance_line = 258.14143410154054
(200, 222.0)
distance_line = 111.12605455067681
(300, 333.0)
distance_line = 30.805843601498726
_____________________________________________
(200, 222.0)
200
...........
(461.5, 281.0)
distance_line = 353.8954647915116
(275.0, 282.0)
distance_line = 91.83681179135085
(300, 333.0)
distance_line = 126.82271089990152
_____________________________________________
(300, 333.0)
300
...........
(461.5, 281.0)
distance_line = 205.6817930688081
(275.0, 282.0)
distance_line = 63.15853069855251
(200, 222.0)
distance_line = 166.4001201922643
_____________________________________________


In [6]:
count_Subtract = np.subtract(list_A[0], list_A[1])
print(count_Subtract)

[186.5  -1. ]


In [7]:
type(count_Subtract)

numpy.ndarray

In [10]:
count_Subtract[0]

186.5

In [9]:
from operator import sub
c = tuple(map(sub, list_A[0], list_A[1]))
c

(186.5, -1.0)

In [27]:
P1 = (int(10),int(10))
P2 = (int(100),int(200))
distance_line = np.subtract(P2, P1)
distance_line

array([ 90, 190])

In [28]:
P1

(10, 10)

In [31]:
dist = np.sqrt((P2[0] - P1[0])**2 + (P2[0] - P1[1])**2)
print(dist)

127.27922061357856


## distances sklearn

In [2]:
import numpy as np
from sklearn.metrics import pairwise_distances

In [3]:
list_B = [(461.5, 281.0), (275.0, 282.0), (200, 222.0), (300, 333.0)] #centerCount_list

In [4]:
distance_sklearn = pairwise_distances(list_B)
print(type(distance_sklearn))
print(distance_sklearn)

<class 'numpy.ndarray'>
[[  0.         186.50268095 268.07321761 169.66511132]
 [186.50268095   0.          96.04686356  56.79788728]
 [268.07321761  96.04686356   0.         149.40214189]
 [169.66511132  56.79788728 149.40214189   0.        ]]


In [5]:
distance_sklearn[1]

array([186.50268095,   0.        ,  96.04686356,  56.79788728])

In [6]:
list_B[0]

(461.5, 281.0)

In [16]:
for i, output_i in enumerate(distance_sklearn):
    for ii, output_ii in enumerate(output_i):
        if 0 < output_ii < 160:
            print(i)
            print(ii)
            print(output_ii)

1
2
96.04686356149273
1
3
56.79788728465171
2
1
96.04686356149273
2
3
149.40214188558343
3
1
56.79788728465171
3
2
149.40214188558343


In [27]:
# Check by numpy where

In [28]:
Index_Check = np.where(distance_sklearn < 160)
print(Index_Check)
print(Index_Check[0])
print(Index_Check[1])
print(Index_Check[1][2])

(array([0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64), array([0, 1, 2, 3, 1, 2, 3, 1, 2, 3], dtype=int64))
[0 1 1 1 2 2 2 3 3 3]
[0 1 2 3 1 2 3 1 2 3]
2


In [30]:
for k, output_k in enumerate(Index_Check[0]):
    if Index_Check[1][k] != output_k:
        print(output_k) #P1
        print(list_B[output_k])
        print('--------------')
        print(Index_Check[1][k])#P2
        print(list_B[Index_Check[1][k]])

1
(275.0, 282.0)
--------------
2
(200, 222.0)
1
(275.0, 282.0)
--------------
3
(300, 333.0)
2
(200, 222.0)
--------------
1
(275.0, 282.0)
2
(200, 222.0)
--------------
3
(300, 333.0)
3
(300, 333.0)
--------------
1
(275.0, 282.0)
3
(300, 333.0)
--------------
2
(200, 222.0)
